# Generated by Django 3.0.8 on 2020-10-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200930_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='user',
        ),
    ]
