# Generated by Django 3.0.8 on 2020-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_cart_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
