# Generated by Django 3.0.8 on 2020-10-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_products_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
