# Generated by Django 3.0.8 on 2020-10-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_cart_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
