# Generated by Django 3.0.8 on 2020-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_cart_items_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
