# Generated by Django 3.0.8 on 2020-10-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20201020_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Users'),
        ),
    ]
