# Generated by Django 3.0.8 on 2021-06-12 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_cart_items_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.cart_items'),
        ),
    ]
