# Generated by Django 3.0.8 on 2021-06-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20210612_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart_items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Users'),
        ),
    ]
