# Generated by Django 3.0.8 on 2021-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20210612_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(blank=True, choices=[('mobiles', 'MOBILES'), ('tablet', 'TABLET'), ('laptop', 'LAPTOP')], max_length=20, null=True),
        ),
    ]
